Update GameEngine.java
AAAlex-123/Tic-Tab-Toe-Online pull request #17
Opened 2020-09-27 14:52 UTC by dimits-exe

owo

2020-09-27 14:57 UTC, dimits-exe commented
Changes:
Server.getServerOptions()-> boardSize
boardSize -> GameBoard.<init>(boardSize)
Server-> GameEngine(boardSize/GameBoard instance)->UI.<init>(boardSize)

2020-09-27 15:05 UTC, AAAlex-123 commented on GameBoard.java
> +	public final int size;
γτ public

2020-09-27 15:07 UTC, AAAlex-123 commented on GameEngine.java
> +	private int server,boardSize=8;//TODO: make this value dependent on the server upon initialization
αποφάσισε τι όνομα θα έχει αυτή η ^@(*#Θ@! μεταβλητή επιτέλους λμαο

2020-09-27 15:09 UTC, AAAlex-123 commented on GameUI.java
> +				if (!input.matches(String.format("[A-%s][1-5]",letters[boardSize]))) {
if (!input.matches(String.format("[A-%s][1-5]",letters[boardSize]))) {
να γίνει
if (!input.matches(String.format("[A-%s][1-%d]",letters[boardSize], boardSize))) {
να αλλάξουν κ οι δύο συντεταγμένες

2020-09-27 15:11 UTC, AAAlex-123 commented on GameEngine.java
> +	private int server,boardSize=8;//TODO: make this value dependent on the server upon initialization
^ αλλά είναι σωστό, είναι παντού το ίδιο το όνομα

2020-09-27 15:18 UTC, AAAlex-123 commented on GameUI.java
> +	private String[] letters = { "A", "B", "C", "D", "E","F","G","H"};
γτ βγήκε έξω το letters;

2020-09-27 15:20 UTC, AAAlex-123 requested changes
owo ti kanei to "request changes'

2020-09-27 15:20 UTC, AAAlex-123 approved these changes

2020-09-29 08:17 UTC, AAAlex-123 approved these changes
if it works it works

2020-09-29 12:38 UTC, merged